version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/conf/php-fpm.d
      - ./:/var/www
      - "phpsocket:/var/run"
    ports:
      - '8000:80'
    depends_on:
      - db
    environment:
      - TZ="Asia/Yekaterinburg"

  nginx:
    image: nginx:latest
    depends_on:
      - php
    ports:
      - "8500:80"
    volumes:
      - ./docker/conf/nginx/conf.d/etc/nginx/conf.d
      - ./docker/conf/nginx/nginx.conf
      - ./web:/var/www/web
      - ./runtime/logs/nginx:/var/log/nginx:delegated
      - "phpsocket:/var/run"

  db:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
volumes:
  phpsocket:
  db: